//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.GameJamService"/> </summary
    public sealed class GameJamServiceClient : Beamable.Server.MicroserviceClient
    {
        
        /// <summary>
        /// Call the Multiply method on the GameJamService microservice
        /// <see cref="Beamable.Server.GameJamService.Multiply"/>
        /// </summary>
        public Beamable.Common.Promise<int> Multiply(int x, int y)
        {
            string serialized_x = this.SerializeArgument<int>(x);
            string serialized_y = this.SerializeArgument<int>(y);
            string[] serializedFields = new string[] {
                    serialized_x,
                    serialized_y};
            return this.Request<int>("GameJamService", "Multiply", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersGameJamServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : Beamable.Server.MicroserviceClientDataWrapper<int>
        {
        }
    }
}
